# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d4c2886ef64cd4f6479e529bf6f0c59bfbbdb919fc01c3b3c0e9ec778d3a81d76d3942cb79f732dc65ad076401743e263cd57967b3717a589f7f7580fca37ad

test:
  secret_key_base: e64277d89cb9241ab53762595b67d53eb332678b231f442d88dfed8ba6830b2c43a53411a08c3c51c0817c0c874346040701c92df7a8a54802b78179150ebd63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
